<script setup lang="ts">
import { Form, Head, router } from '@inertiajs/vue3';
import { computed, ref } from 'vue';
import { CheckCircle2, Pencil, Plus, Search, Trash2, Users, Wrench, X } from '@lucide/vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

type Zone = { id: number; name: string };
type Space = { id: number; zone_id: number; zone_name: string | null; name: string; capacity: number | null; status: 'available' | 'maintenance'; created_at: string | null };
type LinkItem = { url: string | null; label: string; active: boolean };
type Props = { spaces: { data: Space[]; current_page: number; last_page: number; total: number; links: LinkItem[] }; zones: Zone[]; filters: { search: string; status: string; zone_id: string }; stats: { total: number; available: number; maintenance: number } };
const props = defineProps<Props>();
const showForm = ref(false); const editing = ref<Space | null>(null); const formKey = ref(0);
const search = ref(props.filters.search ?? ''); const status = ref(props.filters.status ?? 'all'); const zoneId = ref(props.filters.zone_id ?? 'all');
const title = computed(() => editing.value ? 'Edit zone space' : 'Add new zone space');
const action = computed(() => editing.value ? `/zone-spaces/${editing.value.id}` : '/zone-spaces');
const method = computed(() => editing.value ? 'put' : 'post');
function openCreate() { editing.value = null; formKey.value++; showForm.value = true; }
function openEdit(space: Space) { editing.value = space; formKey.value++; showForm.value = true; }
function closeForm() { showForm.value = false; editing.value = null; }
function filter() { router.get('/zone-spaces', { search: search.value || undefined, status: status.value === 'all' ? undefined : status.value, zone_id: zoneId.value === 'all' ? undefined : zoneId.value }, { preserveState: true, replace: true }); }
function reset() { search.value = ''; status.value = 'all'; zoneId.value = 'all'; filter(); }
function removeSpace(space: Space) { if (!window.confirm(`Hapus zone space ${space.name}?`)) return; router.delete(`/zone-spaces/${space.id}`, { preserveScroll: true }); }
function formatDate(value: string | null) { if (!value) return '—'; return new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)); }
</script>

<template>
<Head title="Zone Spaces" />
<div class="space-y-6 p-4 md:p-6">
  <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-medium text-primary">Master Data</p><h1 class="mt-1 text-2xl font-semibold tracking-tight">Zone Spaces</h1><p class="mt-1 text-sm text-muted-foreground">Kelola area, lapangan, meja, atau space di setiap zone.</p></div><Button @click="openCreate"><Plus class="mr-2 size-4" /> Add zone space</Button></div>
  <div class="grid gap-3 sm:grid-cols-3"><div class="rounded-2xl border bg-card p-4 shadow-sm"><div class="flex justify-between"><span class="text-sm text-muted-foreground">Total spaces</span><Users class="size-4 text-muted-foreground" /></div><div class="mt-3 text-2xl font-semibold">{{ props.stats.total }}</div></div><div class="rounded-2xl border bg-card p-4 shadow-sm"><div class="flex justify-between"><span class="text-sm text-muted-foreground">Available</span><CheckCircle2 class="size-4 text-muted-foreground" /></div><div class="mt-3 text-2xl font-semibold">{{ props.stats.available }}</div></div><div class="rounded-2xl border bg-card p-4 shadow-sm"><div class="flex justify-between"><span class="text-sm text-muted-foreground">Maintenance</span><Wrench class="size-4 text-muted-foreground" /></div><div class="mt-3 text-2xl font-semibold">{{ props.stats.maintenance }}</div></div></div>
  <div class="rounded-2xl border bg-card shadow-sm"><div class="flex flex-col gap-3 border-b p-4 lg:flex-row lg:items-center"><div class="relative flex-1"><Search class="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input v-model="search" @keyup.enter="filter" class="pl-9" placeholder="Search zone space..." /></div><select v-model="zoneId" class="h-10 rounded-md border bg-background px-3 text-sm"><option value="all">All zones</option><option v-for="zone in props.zones" :key="zone.id" :value="String(zone.id)">{{ zone.name }}</option></select><select v-model="status" class="h-10 rounded-md border bg-background px-3 text-sm"><option value="all">All status</option><option value="available">Available</option><option value="maintenance">Maintenance</option></select><Button variant="secondary" @click="filter">Filter</Button><Button variant="ghost" @click="reset">Reset</Button></div>
  <div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-muted/40 text-left text-xs uppercase tracking-wide text-muted-foreground"><tr><th class="px-5 py-3 font-medium">Space</th><th class="px-5 py-3 font-medium">Zone</th><th class="px-5 py-3 font-medium">Capacity</th><th class="px-5 py-3 font-medium">Status</th><th class="px-5 py-3 font-medium">Created</th><th class="px-5 py-3 text-right font-medium">Action</th></tr></thead><tbody class="divide-y"><tr v-for="space in props.spaces.data" :key="space.id" class="hover:bg-muted/20"><td class="px-5 py-4"><div class="font-medium">{{ space.name }}</div><div class="text-xs text-muted-foreground">Space #{{ space.id }}</div></td><td class="px-5 py-4 font-medium">{{ space.zone_name ?? '—' }}</td><td class="px-5 py-4 text-muted-foreground">{{ space.capacity ?? '—' }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-medium" :class="space.status === 'available' ? 'bg-emerald-500/10 text-emerald-600' : 'bg-amber-500/10 text-amber-600'">{{ space.status === 'available' ? 'Available' : 'Maintenance' }}</span></td><td class="px-5 py-4 text-muted-foreground">{{ formatDate(space.created_at) }}</td><td class="px-5 py-4"><div class="flex justify-end gap-1"><Button variant="ghost" size="icon" title="Edit" @click="openEdit(space)"><Pencil class="size-4" /></Button><Button variant="ghost" size="icon" title="Delete" @click="removeSpace(space)"><Trash2 class="size-4 text-destructive" /></Button></div></td></tr><tr v-if="props.spaces.data.length === 0"><td colspan="6" class="px-5 py-16 text-center"><Users class="mx-auto size-10 text-muted-foreground/50" /><p class="mt-3 font-medium">No zone spaces found</p><p class="mt-1 text-sm text-muted-foreground">Coba ubah filter atau tambahkan zone space baru.</p></td></tr></tbody></table></div>
  <div v-if="props.spaces.last_page > 1" class="flex flex-col gap-3 border-t p-4 sm:flex-row sm:items-center sm:justify-between"><p class="text-xs text-muted-foreground">Page {{ props.spaces.current_page }} of {{ props.spaces.last_page }} · {{ props.spaces.total }} spaces</p><div class="flex flex-wrap gap-1"><a v-for="link in props.spaces.links" :key="link.label" :href="link.url ?? '#'" @click.prevent="link.url && router.get(link.url, {}, { preserveState: true })"><Button size="sm" :variant="link.active ? 'default' : 'outline'" :disabled="!link.url" v-html="link.label" /></a></div></div></div>
</div>
<div v-if="showForm" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" @click.self="closeForm"><div class="w-full max-w-lg overflow-hidden rounded-2xl border bg-background shadow-2xl"><div class="flex items-start justify-between border-b p-5"><div><p class="text-sm font-medium text-primary">Zone space management</p><h2 class="mt-1 text-xl font-semibold">{{ title }}</h2><p class="mt-1 text-sm text-muted-foreground">Sesuai struktur tabel <code>zone_spaces</code>.</p></div><Button variant="ghost" size="icon" @click="closeForm"><X class="size-4" /></Button></div><Form :key="formKey" :action="action" :method="method" class="space-y-5 p-5" @success="closeForm" v-slot="{ errors, processing }"><div class="grid gap-4"><div class="grid gap-2"><Label for="zone-space-zone">Zone</Label><select id="zone-space-zone" name="zone_id" :value="editing?.zone_id ?? ''" required class="h-10 rounded-md border bg-background px-3 text-sm"><option value="" disabled>Select zone</option><option v-for="zone in props.zones" :key="zone.id" :value="zone.id">{{ zone.name }}</option></select><p v-if="errors.zone_id" class="text-xs text-destructive">{{ errors.zone_id }}</p></div><div class="grid gap-2"><Label for="zone-space-name">Space name</Label><Input id="zone-space-name" name="name" :default-value="editing?.name" required placeholder="e.g. Padel A" /><p v-if="errors.name" class="text-xs text-destructive">{{ errors.name }}</p></div><div class="grid gap-2"><Label for="capacity">Capacity</Label><Input id="capacity" name="capacity" type="number" min="0" :default-value="editing?.capacity ?? ''" placeholder="e.g. 10" /><p v-if="errors.capacity" class="text-xs text-destructive">{{ errors.capacity }}</p></div><div class="grid gap-2"><Label for="space-status">Status</Label><select id="space-status" name="status" :value="editing?.status ?? 'available'" required class="h-10 rounded-md border bg-background px-3 text-sm"><option value="available">Available</option><option value="maintenance">Maintenance</option></select><p v-if="errors.status" class="text-xs text-destructive">{{ errors.status }}</p></div></div><div class="flex justify-end gap-2 border-t pt-4"><Button type="button" variant="ghost" @click="closeForm">Cancel</Button><Button type="submit" :disabled="processing">{{ processing ? 'Saving...' : editing ? 'Save changes' : 'Create zone space' }}</Button></div></Form></div></div>
</template>
