<script setup lang="ts">
import { Form, Head, router } from '@inertiajs/vue3';
import { computed, ref } from 'vue';
import { CircleDollarSign, Pencil, Plus, Search, Trash2, X } from '@lucide/vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

type ZoneSpace = { id: number; zone_id: number; name: string; zone?: { id: number; name: string } | null };
type Rate = { id: number; zone_space_id: number; zone_space_name: string | null; rental_type: string; price: string | number; created_at: string | null };
type LinkItem = { url: string | null; label: string; active: boolean };
type Props = { rates: { data: Rate[]; current_page: number; last_page: number; total: number; links: LinkItem[] }; zoneSpaces: ZoneSpace[]; filters: { search: string; zone_space_id: string }; stats: { total: number; zoneSpaces: number } };
const props = defineProps<Props>();
const showForm = ref(false); const editing = ref<Rate | null>(null); const formKey = ref(0);
const search = ref(props.filters.search ?? ''); const zoneSpaceId = ref(props.filters.zone_space_id ?? 'all');
const title = computed(() => editing.value ? 'Edit pricing rate' : 'Add new pricing rate');
const action = computed(() => editing.value ? `/pricing-rates/${editing.value.id}` : '/pricing-rates');
const method = computed(() => editing.value ? 'put' : 'post');
function openCreate() { editing.value = null; formKey.value++; showForm.value = true; }
function openEdit(rate: Rate) { editing.value = rate; formKey.value++; showForm.value = true; }
function closeForm() { showForm.value = false; editing.value = null; }
function filter() { router.get('/pricing-rates', { search: search.value || undefined, zone_space_id: zoneSpaceId.value === 'all' ? undefined : zoneSpaceId.value }, { preserveState: true, replace: true }); }
function reset() { search.value = ''; zoneSpaceId.value = 'all'; filter(); }
function removeRate(rate: Rate) { if (!window.confirm(`Hapus pricing rate ${rate.rental_type}?`)) return; router.delete(`/pricing-rates/${rate.id}`, { preserveScroll: true }); }
function formatDate(value: string | null) { if (!value) return '—'; return new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)); }
function formatPrice(value: string | number) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value)); }
</script>

<template>
<Head title="Pricing Rates" />
<div class="space-y-6 p-4 md:p-6">
  <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-medium text-primary">Master Data</p><h1 class="mt-1 text-2xl font-semibold tracking-tight">Pricing Rates</h1><p class="mt-1 text-sm text-muted-foreground">Kelola tarif sewa untuk setiap zone space.</p></div><Button @click="openCreate"><Plus class="mr-2 size-4" /> Add pricing rate</Button></div>
  <div class="grid gap-3 sm:grid-cols-2"><div class="rounded-2xl border bg-card p-4 shadow-sm"><div class="flex justify-between"><span class="text-sm text-muted-foreground">Total rates</span><CircleDollarSign class="size-4 text-muted-foreground" /></div><div class="mt-3 text-2xl font-semibold">{{ props.stats.total }}</div></div><div class="rounded-2xl border bg-card p-4 shadow-sm"><div class="flex justify-between"><span class="text-sm text-muted-foreground">Zone spaces priced</span><CircleDollarSign class="size-4 text-muted-foreground" /></div><div class="mt-3 text-2xl font-semibold">{{ props.stats.zoneSpaces }}</div></div></div>
  <div class="rounded-2xl border bg-card shadow-sm"><div class="flex flex-col gap-3 border-b p-4 lg:flex-row lg:items-center"><div class="relative flex-1"><Search class="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input v-model="search" @keyup.enter="filter" class="pl-9" placeholder="Search pricing rate..." /></div><select v-model="zoneSpaceId" class="h-10 rounded-md border bg-background px-3 text-sm"><option value="all">All zone spaces</option><option v-for="space in props.zoneSpaces" :key="space.id" :value="String(space.id)">{{ space.name }}{{ space.zone?.name ? ` · ${space.zone.name}` : '' }}</option></select><Button variant="secondary" @click="filter">Filter</Button><Button variant="ghost" @click="reset">Reset</Button></div>
  <div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-muted/40 text-left text-xs uppercase tracking-wide text-muted-foreground"><tr><th class="px-5 py-3 font-medium">Zone Space</th><th class="px-5 py-3 font-medium">Rental Type</th><th class="px-5 py-3 font-medium">Price</th><th class="px-5 py-3 font-medium">Created</th><th class="px-5 py-3 text-right font-medium">Action</th></tr></thead><tbody class="divide-y"><tr v-for="rate in props.rates.data" :key="rate.id" class="hover:bg-muted/20"><td class="px-5 py-4"><div class="font-medium">{{ rate.zone_space_name ?? '—' }}</div><div class="text-xs text-muted-foreground">Space #{{ rate.zone_space_id }}</div></td><td class="px-5 py-4">{{ rate.rental_type }}</td><td class="px-5 py-4 font-semibold">{{ formatPrice(rate.price) }}</td><td class="px-5 py-4 text-muted-foreground">{{ formatDate(rate.created_at) }}</td><td class="px-5 py-4"><div class="flex justify-end gap-1"><Button variant="ghost" size="icon" title="Edit" @click="openEdit(rate)"><Pencil class="size-4" /></Button><Button variant="ghost" size="icon" title="Delete" @click="removeRate(rate)"><Trash2 class="size-4 text-destructive" /></Button></div></td></tr><tr v-if="props.rates.data.length === 0"><td colspan="5" class="px-5 py-16 text-center"><CircleDollarSign class="mx-auto size-10 text-muted-foreground/50" /><p class="mt-3 font-medium">No pricing rates found</p><p class="mt-1 text-sm text-muted-foreground">Coba ubah filter atau tambahkan pricing rate baru.</p></td></tr></tbody></table></div>
  <div v-if="props.rates.last_page > 1" class="flex flex-col gap-3 border-t p-4 sm:flex-row sm:items-center sm:justify-between"><p class="text-xs text-muted-foreground">Page {{ props.rates.current_page }} of {{ props.rates.last_page }} · {{ props.rates.total }} rates</p><div class="flex flex-wrap gap-1"><a v-for="link in props.rates.links" :key="link.label" :href="link.url ?? '#'" @click.prevent="link.url && router.get(link.url, {}, { preserveState: true })"><Button size="sm" :variant="link.active ? 'default' : 'outline'" :disabled="!link.url" v-html="link.label" /></a></div></div></div>
</div>
<div v-if="showForm" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" @click.self="closeForm"><div class="w-full max-w-lg overflow-hidden rounded-2xl border bg-background shadow-2xl"><div class="flex items-start justify-between border-b p-5"><div><p class="text-sm font-medium text-primary">Pricing management</p><h2 class="mt-1 text-xl font-semibold">{{ title }}</h2><p class="mt-1 text-sm text-muted-foreground">Sesuai struktur tabel <code>pricing_rates</code>.</p></div><Button variant="ghost" size="icon" @click="closeForm"><X class="size-4" /></Button></div><Form :key="formKey" :action="action" :method="method" class="space-y-5 p-5" @success="closeForm" v-slot="{ errors, processing }"><div class="grid gap-4"><div class="grid gap-2"><Label for="pricing-space">Zone Space</Label><select id="pricing-space" name="zone_space_id" :value="editing?.zone_space_id ?? ''" required class="h-10 rounded-md border bg-background px-3 text-sm"><option value="" disabled>Select zone space</option><option v-for="space in props.zoneSpaces" :key="space.id" :value="space.id">{{ space.name }}{{ space.zone?.name ? ` · ${space.zone.name}` : '' }}</option></select><p v-if="errors.zone_space_id" class="text-xs text-destructive">{{ errors.zone_space_id }}</p></div><div class="grid gap-2"><Label for="rental-type">Rental Type</Label><Input id="rental-type" name="rental_type" :default-value="editing?.rental_type" required placeholder="e.g. Per Hour" /><p v-if="errors.rental_type" class="text-xs text-destructive">{{ errors.rental_type }}</p></div><div class="grid gap-2"><Label for="price">Price</Label><Input id="price" name="price" type="number" min="0" step="0.01" :default-value="editing?.price" required placeholder="e.g. 50000" /><p v-if="errors.price" class="text-xs text-destructive">{{ errors.price }}</p></div></div><div class="flex justify-end gap-2 border-t pt-4"><Button type="button" variant="ghost" @click="closeForm">Cancel</Button><Button type="submit" :disabled="processing">{{ processing ? 'Saving...' : editing ? 'Save changes' : 'Create pricing rate' }}</Button></div></Form></div></div>
</template>
