<script setup lang="ts">
import { Form, Head, router } from '@inertiajs/vue3';
import { ref } from 'vue';
import { BadgeCheck, CalendarDays, CreditCard, Pencil, Plus, Search, Trash2, Users, X } from '@lucide/vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

type Member = { id: number; name: string; email: string };
type Package = { id: number; name: string; price: string | number; duration_days: number };
type Subscription = { id: number; user: Member | null; package: Package | null; start_date: string; end_date: string; status: 'active' | 'expired' | 'cancelled' };
type LinkItem = { url: string | null; label: string; active: boolean };
type Props = { subscriptions: { data: Subscription[]; current_page: number; last_page: number; total: number; links: LinkItem[] }; members: Member[]; packages: Package[]; filters: { search: string; status: string }; stats: { total: number; active: number; expired: number; cancelled: number } };
const props = defineProps<Props>();
const showForm = ref(false); const editing = ref<Subscription | null>(null); const formKey = ref(0);
const search = ref(props.filters.search ?? ''); const status = ref(props.filters.status ?? 'all');
const openCreate = () => { editing.value = null; formKey.value++; showForm.value = true; };
const openEdit = (item: Subscription) => { editing.value = item; formKey.value++; showForm.value = true; };
const closeForm = () => { showForm.value = false; editing.value = null; };
const filter = () => router.get('/memberships', { search: search.value || undefined, status: status.value === 'all' ? undefined : status.value }, { preserveState: true, replace: true });
const reset = () => { search.value = ''; status.value = 'all'; filter(); };
const remove = (item: Subscription) => { if (window.confirm(`Hapus membership ${item.user?.name ?? ''}?`)) router.delete(`/memberships/${item.id}`, { preserveScroll: true }); };
const formatDate = (value: string) => new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value));
const formatPrice = (value: string | number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value));
</script>

<template>
<Head title="Membership" />
<div class="space-y-6 p-4 md:p-6">
  <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-medium text-primary">Membership</p><h1 class="mt-1 text-2xl font-semibold tracking-tight">Member Registration</h1><p class="mt-1 text-sm text-muted-foreground">Daftarkan data user Member sekaligus pilih paket membership.</p></div><Button @click="openCreate"><Plus class="mr-2 size-4" /> Register Member</Button></div>
  <div class="grid gap-3 sm:grid-cols-4"><div v-for="item in [{label:'Total',value:props.stats.total,icon:Users},{label:'Active',value:props.stats.active,icon:BadgeCheck},{label:'Expired',value:props.stats.expired,icon:CalendarDays},{label:'Cancelled',value:props.stats.cancelled,icon:X}]" :key="item.label" class="rounded-2xl border bg-card p-4 shadow-sm"><div class="flex justify-between"><span class="text-sm text-muted-foreground">{{ item.label }}</span><component :is="item.icon" class="size-4 text-muted-foreground" /></div><div class="mt-3 text-2xl font-semibold">{{ item.value }}</div></div></div>
  <div class="rounded-2xl border bg-card shadow-sm"><div class="flex flex-col gap-3 border-b p-4 md:flex-row md:items-center"><div class="relative flex-1"><Search class="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input v-model="search" @keyup.enter="filter" class="pl-9" placeholder="Search member..." /></div><select v-model="status" class="h-10 rounded-md border bg-background px-3 text-sm"><option value="all">All status</option><option value="active">Active</option><option value="expired">Expired</option><option value="cancelled">Cancelled</option></select><Button variant="secondary" @click="filter">Filter</Button><Button variant="ghost" @click="reset">Reset</Button></div>
  <div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-muted/40 text-left text-xs uppercase tracking-wide text-muted-foreground"><tr><th class="px-5 py-3 font-medium">Member</th><th class="px-5 py-3 font-medium">Package</th><th class="px-5 py-3 font-medium">Period</th><th class="px-5 py-3 font-medium">Status</th><th class="px-5 py-3 text-right font-medium">Action</th></tr></thead><tbody class="divide-y"><tr v-for="item in props.subscriptions.data" :key="item.id" class="hover:bg-muted/20"><td class="px-5 py-4"><div class="font-medium">{{ item.user?.name ?? '—' }}</div><div class="text-xs text-muted-foreground">{{ item.user?.email ?? '—' }}</div></td><td class="px-5 py-4"><div class="font-medium">{{ item.package?.name ?? '—' }}</div><div v-if="item.package" class="text-xs text-muted-foreground">{{ formatPrice(item.package.price) }} · {{ item.package.duration_days }} hari</div></td><td class="px-5 py-4 text-muted-foreground">{{ formatDate(item.start_date) }} — {{ formatDate(item.end_date) }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-medium" :class="item.status === 'active' ? 'bg-emerald-500/10 text-emerald-600' : item.status === 'expired' ? 'bg-amber-500/10 text-amber-600' : 'bg-muted text-muted-foreground'">{{ item.status.charAt(0).toUpperCase() + item.status.slice(1) }}</span></td><td class="px-5 py-4"><div class="flex justify-end gap-1"><Button variant="ghost" size="icon" title="Edit" @click="openEdit(item)"><Pencil class="size-4" /></Button><Button variant="ghost" size="icon" title="Delete" @click="remove(item)"><Trash2 class="size-4 text-destructive" /></Button></div></td></tr><tr v-if="props.subscriptions.data.length === 0"><td colspan="5" class="px-5 py-16 text-center"><CreditCard class="mx-auto size-10 text-muted-foreground/50" /><p class="mt-3 font-medium">No membership registration found</p><p class="mt-1 text-sm text-muted-foreground">Belum ada member yang didaftarkan.</p></td></tr></tbody></table></div>
  <div v-if="props.subscriptions.last_page > 1" class="flex flex-col gap-3 border-t p-4 sm:flex-row sm:items-center sm:justify-between"><p class="text-xs text-muted-foreground">Page {{ props.subscriptions.current_page }} of {{ props.subscriptions.last_page }} · {{ props.subscriptions.total }} registrations</p><div class="flex flex-wrap gap-1"><a v-for="link in props.subscriptions.links" :key="link.label" :href="link.url ?? '#'" @click.prevent="link.url && router.get(link.url, {}, { preserveState: true })"><Button size="sm" :variant="link.active ? 'default' : 'outline'" :disabled="!link.url" v-html="link.label" /></a></div></div></div>
</div>
<div v-if="showForm" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" @click.self="closeForm"><div class="w-full max-w-2xl overflow-hidden rounded-2xl border bg-background shadow-2xl"><div class="flex items-start justify-between border-b p-5"><div><p class="text-sm font-medium text-primary">{{ editing ? 'Membership' : 'New Member + Membership' }}</p><h2 class="mt-1 text-xl font-semibold">{{ editing ? 'Edit Membership' : 'Register Member' }}</h2><p class="mt-1 text-sm text-muted-foreground">{{ editing ? 'Perbarui paket dan periode membership member.' : 'Data user dan membership didaftarkan sekaligus dalam satu form.' }}</p></div><Button variant="ghost" size="icon" @click="closeForm"><X class="size-4" /></Button></div><Form :key="formKey" :action="editing ? `/memberships/${editing.id}` : '/memberships'" :method="editing ? 'put' : 'post'" class="space-y-5 p-5" @success="closeForm" v-slot="{ errors, processing }">
  <div v-if="!editing" class="space-y-4 rounded-xl border bg-muted/20 p-4"><div><h3 class="font-semibold">Data Member</h3><p class="text-xs text-muted-foreground">User baru otomatis dibuat dengan role Member.</p></div><div class="grid gap-4 sm:grid-cols-2"><div class="grid gap-2"><Label>Nama</Label><Input name="name" placeholder="Nama lengkap" required /><p v-if="errors.name" class="text-xs text-destructive">{{ errors.name }}</p></div><div class="grid gap-2"><Label>Email</Label><Input name="email" type="email" placeholder="member@email.com" required /><p v-if="errors.email" class="text-xs text-destructive">{{ errors.email }}</p></div><div class="grid gap-2"><Label>No. Telepon</Label><Input name="phone" placeholder="08xxxxxxxxxx" /><p v-if="errors.phone" class="text-xs text-destructive">{{ errors.phone }}</p></div><div class="grid gap-2"><Label>Password</Label><Input name="password" type="password" placeholder="Minimal 8 karakter" required /><p v-if="errors.password" class="text-xs text-destructive">{{ errors.password }}</p></div></div></div>
  <div v-else class="rounded-xl border bg-muted/20 p-4"><p class="text-xs text-muted-foreground">Member</p><p class="mt-1 font-medium">{{ editing.user?.name }}</p><p class="text-xs text-muted-foreground">{{ editing.user?.email }}</p></div>
  <div class="space-y-4"><h3 class="font-semibold">Membership</h3><div class="grid gap-4 sm:grid-cols-2"><div class="grid gap-2 sm:col-span-2"><Label>Membership Package</Label><select name="membership_package_id" :value="editing?.package?.id ?? ''" required class="h-10 rounded-md border bg-background px-3 text-sm"><option value="" disabled>Select package</option><option v-for="pkg in props.packages" :key="pkg.id" :value="pkg.id">{{ pkg.name }} — {{ formatPrice(pkg.price) }} / {{ pkg.duration_days }} hari</option></select><p v-if="errors.membership_package_id" class="text-xs text-destructive">{{ errors.membership_package_id }}</p></div><div class="grid gap-2"><Label>Start Date</Label><Input name="start_date" type="date" :default-value="editing?.start_date" required /><p v-if="errors.start_date" class="text-xs text-destructive">{{ errors.start_date }}</p></div><div class="grid gap-2"><Label>End Date</Label><Input name="end_date" type="date" :default-value="editing?.end_date" required /><p v-if="errors.end_date" class="text-xs text-destructive">{{ errors.end_date }}</p></div><div class="grid gap-2 sm:col-span-2"><Label>Status</Label><select name="status" :value="editing?.status ?? 'active'" required class="h-10 rounded-md border bg-background px-3 text-sm"><option value="active">Active</option><option value="expired">Expired</option><option value="cancelled">Cancelled</option></select><p v-if="errors.status" class="text-xs text-destructive">{{ errors.status }}</p></div></div></div>
  <div class="flex justify-end gap-2 border-t pt-4"><Button type="button" variant="ghost" @click="closeForm">Cancel</Button><Button type="submit" :disabled="processing">{{ processing ? 'Saving...' : editing ? 'Save changes' : 'Register member' }}</Button></div>
</Form></div></div>
</template>
