<script setup lang="ts">
import { Form, Head, router } from '@inertiajs/vue3';
import { ref } from 'vue';
import { Pencil, Plus, Search, Trash2, UserRoundPlus, Users, X } from '@lucide/vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

type Member = { id: number; name: string; email: string; phone: string | null; created_at: string };
type LinkItem = { url: string | null; label: string; active: boolean };
type Props = { members: { data: Member[]; current_page: number; last_page: number; total: number; links: LinkItem[] }; filters: { search: string }; stats: { total: number; new_this_month: number } };
const props = defineProps<Props>();
const showForm = ref(false); const editing = ref<Member | null>(null); const formKey = ref(0); const search = ref(props.filters.search ?? '');
const openCreate = () => { editing.value = null; formKey.value++; showForm.value = true; };
const openEdit = (member: Member) => { editing.value = member; formKey.value++; showForm.value = true; };
const closeForm = () => { showForm.value = false; editing.value = null; };
const filter = () => router.get('/memberships', { search: search.value || undefined }, { preserveState: true, replace: true });
const reset = () => { search.value = ''; filter(); };
const remove = (member: Member) => { if (window.confirm(`Nonaktifkan member ${member.name}?`)) router.delete(`/memberships/${member.id}`, { preserveScroll: true }); };
const formatDate = (value: string) => new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value));
</script>

<template>
<Head title="Membership" />
<div class="space-y-6 p-4 md:p-6">
  <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-medium text-primary">Navigation</p><h1 class="mt-1 text-2xl font-semibold tracking-tight">Membership</h1><p class="mt-1 text-sm text-muted-foreground">Registrasi dan pengelolaan data member. Subscription dikelola di modul terpisah.</p></div><Button @click="openCreate"><Plus class="mr-2 size-4" /> Register Member</Button></div>
  <div class="grid gap-3 sm:grid-cols-2"><div class="rounded-2xl border bg-card p-4 shadow-sm"><div class="flex justify-between"><span class="text-sm text-muted-foreground">Total Members</span><Users class="size-4 text-muted-foreground" /></div><div class="mt-3 text-2xl font-semibold">{{ props.stats.total }}</div></div><div class="rounded-2xl border bg-card p-4 shadow-sm"><div class="flex justify-between"><span class="text-sm text-muted-foreground">New This Month</span><UserRoundPlus class="size-4 text-muted-foreground" /></div><div class="mt-3 text-2xl font-semibold">{{ props.stats.new_this_month }}</div></div></div>
  <div class="rounded-2xl border bg-card shadow-sm"><div class="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center"><div class="relative flex-1"><Search class="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input v-model="search" @keyup.enter="filter" class="pl-9" placeholder="Search member..." /></div><Button variant="secondary" @click="filter">Filter</Button><Button variant="ghost" @click="reset">Reset</Button></div>
  <div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-muted/40 text-left text-xs uppercase tracking-wide text-muted-foreground"><tr><th class="px-5 py-3 font-medium">Member</th><th class="px-5 py-3 font-medium">Phone</th><th class="px-5 py-3 font-medium">Registered</th><th class="px-5 py-3 text-right font-medium">Action</th></tr></thead><tbody class="divide-y"><tr v-for="member in props.members.data" :key="member.id" class="hover:bg-muted/20"><td class="px-5 py-4"><div class="font-medium">{{ member.name }}</div><div class="text-xs text-muted-foreground">{{ member.email }}</div></td><td class="px-5 py-4 text-muted-foreground">{{ member.phone || '—' }}</td><td class="px-5 py-4 text-muted-foreground">{{ formatDate(member.created_at) }}</td><td class="px-5 py-4"><div class="flex justify-end gap-1"><Button variant="ghost" size="icon" title="Edit" @click="openEdit(member)"><Pencil class="size-4" /></Button><Button variant="ghost" size="icon" title="Deactivate" @click="remove(member)"><Trash2 class="size-4 text-destructive" /></Button></div></td></tr><tr v-if="props.members.data.length === 0"><td colspan="4" class="px-5 py-16 text-center"><Users class="mx-auto size-10 text-muted-foreground/50" /><p class="mt-3 font-medium">No member found</p><p class="mt-1 text-sm text-muted-foreground">Belum ada member terdaftar.</p></td></tr></tbody></table></div>
  <div v-if="props.members.last_page > 1" class="flex flex-col gap-3 border-t p-4 sm:flex-row sm:items-center sm:justify-between"><p class="text-xs text-muted-foreground">Page {{ props.members.current_page }} of {{ props.members.last_page }} · {{ props.members.total }} members</p><div class="flex flex-wrap gap-1"><a v-for="link in props.members.links" :key="link.label" :href="link.url ?? '#'" @click.prevent="link.url && router.get(link.url, {}, { preserveState: true })"><Button size="sm" :variant="link.active ? 'default' : 'outline'" :disabled="!link.url" v-html="link.label" /></a></div></div></div>
</div>
<div v-if="showForm" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" @click.self="closeForm"><div class="w-full max-w-xl overflow-hidden rounded-2xl border bg-background shadow-2xl"><div class="flex items-start justify-between border-b p-5"><div><p class="text-sm font-medium text-primary">Membership</p><h2 class="mt-1 text-xl font-semibold">{{ editing ? 'Edit Member' : 'Register Member' }}</h2><p class="mt-1 text-sm text-muted-foreground">Registrasi member tidak membuat subscription otomatis.</p></div><Button variant="ghost" size="icon" @click="closeForm"><X class="size-4" /></Button></div><Form :key="formKey" :action="editing ? `/memberships/${editing.id}` : '/memberships'" :method="editing ? 'put' : 'post'" class="space-y-5 p-5" @success="closeForm" v-slot="{ errors, processing }"><div class="grid gap-4 sm:grid-cols-2"><div class="grid gap-2 sm:col-span-2"><Label>Nama Lengkap</Label><Input name="name" :default-value="editing?.name" placeholder="Nama lengkap" required /><p v-if="errors.name" class="text-xs text-destructive">{{ errors.name }}</p></div><div class="grid gap-2"><Label>Email</Label><Input name="email" type="email" :default-value="editing?.email" placeholder="member@email.com" required /><p v-if="errors.email" class="text-xs text-destructive">{{ errors.email }}</p></div><div class="grid gap-2"><Label>No. Telepon</Label><Input name="phone" :default-value="editing?.phone ?? ''" placeholder="08xxxxxxxxxx" /><p v-if="errors.phone" class="text-xs text-destructive">{{ errors.phone }}</p></div><div class="grid gap-2 sm:col-span-2"><Label>{{ editing ? 'Password Baru (opsional)' : 'Password' }}</Label><Input name="password" type="password" :placeholder="editing ? 'Kosongkan jika tidak diubah' : 'Minimal 8 karakter'" :required="!editing" /><p v-if="errors.password" class="text-xs text-destructive">{{ errors.password }}</p></div></div><div class="flex justify-end gap-2 border-t pt-4"><Button type="button" variant="ghost" @click="closeForm">Cancel</Button><Button type="submit" :disabled="processing">{{ processing ? 'Saving...' : editing ? 'Save changes' : 'Register member' }}</Button></div></Form></div></div>
</template>
